from Bio import Seq

def countSeq(template,seq):

    seqLoc = []
    loc = template.rfind(seq)

    while(loc != -1):

        seqLoc.append(loc)
        template=template[:loc+(len(seq)-1)]
        loc = template.rfind(seq)

    return seqLoc

def main():

    a = Seq.Seq('ACTTAAACTATAGGAAACTATAAAAACTATAACCTCAGGGCCGAACTATAGTCGGGTCGCGAACTATACCCAAACTATAGAACTATATCCGACAAAACTATACACATATAACCAAACTATAAACTATACATTTCGGCAGACAAACTATACCATAACTATAAACTATAGAACTATAAAACTATACAACTATATTGGCAACTATAACCAATCGGGAACTATAAAACTATAGAACTATAAACTATAAACTATATAACTATACTAAAGGACTGAACTATACAACTATATGTAACTATATGCGGTTATAACTATAAACTATACAACTATAAACTATATTCAACTATACAACTATAAACTATACGGCCAACTATAGCTAAGAGAACTATATGGAACTATACCTTCGATAACTATACGAACTATATAACTATAAACTATATCATGCACCAGGGCAAACTATAGGTACGGAACTATATTAACTATATTCGGCAACTATAGAAACTATAAACTATATCAACTATAAACTATAGCAGAGTAACTATATGTGTTTTCAACTATAAACTATAACGGAATAACTATACTAGTAGACGAACTATAAACTATAAACTATAAACTATACAACTATAACGAACTATACCGCAACTATACTGCATTGAAACTATAACAACTATAAACTATAAACTATATTTAACAATGAACTATAGGAAACTATATTAAAACTATAAACTATAAACTATACCCGCTTGGTAAGTTAAACTATAAACTATAAACTATATACGGAACTATAGTCTGAAATGCAACTATATTAACTATATCAG')
    b = 'AACTATAAA'

    l=[]
    o = countSeq(a,b)

    for i in range(len(o)):
        l.append(o[-i]+1)

    print(o)
    print(l)


if __name__ == '__main__':
    main()
